### ISSUE TITLE
feat(stretch): `/code` command

### ISSUE THREAD

**Issue by sudojunior** [slash-create/docs-bot#10]
```yaml
"/code | /source":
  file*: string! (auto) # map over docgen entries for file directories and names
  start*: int
  end?: int = from + 4
```

Intention to have a system that can request a code file directly from GitHub, and display it in Discord with appropriate context.
Also knowing where an embed begins forcing line breaks would also be useful to know how code can be *cleanly* divided between line breaks.

> This command isn't as vital as other existing or proposed commands, but continues to serve as a challenge that the framework may offer during its implementation.
